### ISSUE TITLE
Claim of anonymity is misleading

### ISSUE THREAD

**Issue by JeremyRand** [Coinomi/coinomi.github.io#2]
The [Coinomi main page](https://coinomi.com/) includes this quote:

> spending your funds is totally anonymous

This is misleading, since Bitcoin (as well as most of the coins that Coinomi supports) is known to not be anonymous.  (I assume you're at least minimally familiar with this research area; let me know if that's not the case.)

I assume that the intent of that quote is to convey that Coinomi's server acts as a proxy when relaying users' transactions to the Bitcoin network, which prevents third party network nodes from seeing which IP originated the transaction (unless Coinomi's server is compromised, of course).  This definitely does have privacy benefits against some threat models.  But I don't think that it's correct to say that this implies that "spending your funds is totally anonymous".

Can that phrasing be reworded to make the distinction more clear?

Cheers.

**Comment by GeorgeKimionis** [comment]
Fixed.
