### ISSUE TITLE
Zcash support in recovery tool

### ISSUE THREAD

**Issue by cryptowest** [Coinomi/coinomi.github.io#3]
I'm having some problems with my ZEC coinomi wallet and I need to export the private keys, but the recovery tool doesn't have support for Zcash yet. Is this in the works? Thanks

**Comment by erasmospunk** [comment]
Zcash is using different kind of addresses and we haven't added support to the recovery phrase tool.

However it is easy to get your private keys, just enter 133 in the Coin field in the "Derivation Path" section. In the External / Internal field you should use also 1 to get the "change addresses" private keys. Note that the addresses in the Derived Addresses section will not be the same as your Coinomi wallet but the private keys will be the correct ones.

If you have issues with your Coinomi wallet please send us to support [at] coinomi.com
