### ISSUE TITLE
wallet location on android  coinomi 1.6.5

### ISSUE THREAD

**Issue by btc1200** [Coinomi/coinomi.github.io#4]
Hi, I'm looking for my wallet location and file name on my android.  I'm trying to use a pc to android to pull the data off of .  I'm using a program mobile go in developer mode on my android.  If you recommend a better program to use please advise. 
Thanks in advance

**Comment by GeorgeKimionis** [comment]
Coinomi Desktop will be released soon for Windows, Linux and Mac. For further assistance: support@coinomi.com

**Comment by btc1200** [comment]
I'm trying to recover my wallet on my phone using my pc connected to a usb.

**Comment by GeorgeKimionis** [comment]
This isn't the right place to ask, please use: support@coinomi.com.

**Comment by btc1200** [comment]
Ok, sorry.   I'll send email now.  I sent one about 10 days ago and haven't seen a reply yet.

**Comment by GeorgeKimionis** [comment]
What is the e-mail you used?

**Comment by btc1200** [comment]
schmidr12@gmail.com

**Comment by GeorgeKimionis** [comment]
Thanks, an engineer will reply to your inquiry asap.
